### ISSUE TITLE
NameError: name 'Phant' is not defined

### ISSUE THREAD

**Issue by spuder** [matze/python-phant#12]
Having a hard time getting this module to work with python 2.7.3. Following the instructions in the README. 

```
cd /tmp
git clone https://github.com/matze/python-phant.git
cp /tmp/python-phant/phant.py ~/
```

```
python ~/foo.py
raceback (most recent call last):
  File "foo.py", line 42, in <module>
    p = Phant('xxxxx', data['humidity'], data['tempc'], data['tempf'], private_key='xxxxx')
NameError: name 'Phant' is not defined
```

Also tried installing the module with 

   sudo pip install phant

and

    sudo python /tmp/python-phant/setup.py install

The script looks like 

```
import sys
import Adafruit_DHT
import phant
humidity, temperature = Adafruit_DHT.read_retry(sensor, pin)
data = {}
if humidity is not None and temperature is not None:
        data['humidity'] = humidity
        data['tempc'] = temperature
        data['tempf'] = temperature * 9/5.0 + 32
        print data
        p = Phant('xxxxx', data['humidity'], data['tempc'], data['tempf'], private_key='xxxxx')
        p.log(33.4, 10.2)
        print(p.remaining_bytes, p.cap)
else:
        print 'Failed to get reading. Try again!'
        sys.exit(1)
```

Also looking at the tests.py and I see the following syntax. 

                p = phant.Phant(PUBLIC, 'field', private_key=PRIVATE)

That returns the same error. 

Is there an example repo anywhere that shows this library actually being used?

**Comment by matze** [comment]
The `Phant` class is located in the `phant` module, hence you will either have to import it via
```python
from phant import Phant
```
or use it like in the test. Have you tried running the tests?

**Comment by spuder** [comment]
Thank you, got it working and created a pull request to clarify the docs incase any other python noobs get stuck. #13
