### ISSUE TITLE
Error __init__() takes at least 2 arguments (1 given)

### ISSUE THREAD

**Issue by DanOBrien** [matze/python-phant#16]
Trying to play with the python library installed through pip gives me an error.

pi@openthing ~ $ python
Python 2.7.3 (default, Mar 18 2014, 05:13:23)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> from phant import Phant
>>> import phant
>>> p=phant.Phant(jsonPath='/home/pi/phant_key.json')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes at least 2 arguments (1 given)
>>>

This error occurs on both Raspberry Pi and Ubuntu on x86

**Comment by matze** [comment]
The current HEAD version is not yet on PyPI. Installing from source (i.e. `python setup.py install`) should give you the desired result. I am still hesitating to push to PyPI because the current API is not PEP8 conformant.
