### ISSUE TITLE
AttributeError: 'Phant' object has no attribute '_get_url'

### ISSUE THREAD

**Issue by jberthe** [matze/python-phant#18]
Hi,

I've just downloaded the current version, and execute it with Python 2.7 on Synology.

Here is the command line : 
**python testPhant.py**

The file contain the example from Github.

The full error :

> Traceback (most recent call last):
>   File "testPhant.py", line 3, in <module>
>     p = Phant(publicKey='xxxxx', fields=['test1', 'test2'], privateKey='xxxxxxx')
>   File "/usr/local/lib/python2.7/site-packages/phant-0.6dev-py2.7.egg/phant/__init__.py", line 45, in __init__
>     'inputUrl': self._get_url('input', extension=''),
> AttributeError: 'Phant' object has no attribute '_get_url'

Regards,
Joseph

**Comment by jianwel** [comment]
I got the same error. Have you solved it?

**Comment by Justleen** [comment]
Can Confirm, clean install and the example spits out that error.

**Comment by matze** [comment]
Hope #19 fixes it for you guys. Sorry, for being a bit absent lately!
