### ISSUE TITLE
get() - offset and  sample parameters are handled wrong

### ISSUE THREAD

**Issue by gdhamp** [matze/python-phant#8]
if offset:
            if not isinstance(offset, int):
                raise ValueError("Offset must be an int")
            params['offset'] = limit  <<--- Should be offset

        if sample:
            if not isinstance(sample, int):
                raise ValueError("Sample must be an int")
            params['sample'] = limit <<--- Should be sample

**Comment by matze** [comment]
Fixed by #9.
